services:
  database:
    container_name: fennixsdb
    image: postgres:18
    environment:
      POSTGRES_DB: fennixsdb
      POSTGRES_USER: fennixs
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fennixs -d fennixsdb"]
      interval: 10s
      timeout: 5s   
      retries: 5
      start_period: 10s

volumes:
  postgres_data: